// [ BACKEND > PRESENTATION > FMP ERROR STATUS > TESTS ] #############################################
//
// Table-driven tests pinning every provider-error kind to its HTTP status so
// the switch's branches and the default fall-through are each asserted directly
// rather than only through controller integration tests.

// 1.1. EXTERNAL DEPENDENCIES ........................................................................
import assert from "node:assert/strict";
import { describe, it } from "node:test";
// 1.1. END ..........................................................................................

// 1.2. INTERNAL DEPENDENCIES ........................................................................
import { statusForFmpError } from "./index.js";
// 1.2. END ..........................................................................................

// 1.3. MOCKS ........................................................................................
// None required — the mapping is a pure function over the error kind.
// 1.3. END ..........................................................................................

// 1.4. TEST CASES ...................................................................................
describe("statusForFmpError", () => {
  // 1.4.1. MAPS NOT FOUND TO 404 ....................................................................
  it("maps 'not-found' to 404", () => {
    assert.equal(statusForFmpError("not-found"), 404);
  });
  // 1.4.1. END ......................................................................................

  // 1.4.2. MAPS RATE LIMIT TO 429 ...................................................................
  it("maps 'rate-limit' to 429", () => {
    assert.equal(statusForFmpError("rate-limit"), 429);
  });
  // 1.4.2. END ......................................................................................

  // 1.4.3. MAPS TIMEOUT TO 504 ......................................................................
  it("maps 'timeout' to 504", () => {
    assert.equal(statusForFmpError("timeout"), 504);
  });
  // 1.4.3. END ......................................................................................

  // 1.4.4. MAPS AUTHENTICATION TO 502 ...............................................................
  it("maps 'authentication' to 502 via the default branch", () => {
    assert.equal(statusForFmpError("authentication"), 502);
  });
  // 1.4.4. END ......................................................................................

  // 1.4.5. MAPS INVALID RESPONSE TO 502 .............................................................
  it("maps 'invalid-response' to 502 via the default branch", () => {
    assert.equal(statusForFmpError("invalid-response"), 502);
  });
  // 1.4.5. END ......................................................................................

  // 1.4.6. MAPS PROVIDER TO 502 .....................................................................
  it("maps 'provider' to 502 via the default branch", () => {
    assert.equal(statusForFmpError("provider"), 502);
  });
  // 1.4.6. END ......................................................................................
});
// 1.4. END ..........................................................................................

// END FILE ##########################################################################################
