// [ COMPONENTS > STATES > QUALITATIVE PILLARS EMPTY ] ###############################################

// 1.1. EXTERNAL DEPENDENCIES ........................................................................
'use client';

import React from 'react';
// 1.1. END ..........................................................................................

// 1.2. INTERNAL DEPENDENCIES ........................................................................
import {
    QualitativePillarsStateContainer,
    QualitativePillarsStateDescription,
    QualitativePillarsStateTitle,
} from './qualitative-pillars.styles';
// 1.2. END ..........................................................................................

// 1.3. IMAGES .......................................................................................
// 1.3. END ..........................................................................................

// 1.4. DATA .........................................................................................
// 1.4. END ..........................................................................................

// 1.5. TYPES ........................................................................................
interface IQualitativePillarsEmpty {
    message?: string;
    title?: string;
}
// 1.5. END ..........................................................................................

// 1.6. COMPONENT ....................................................................................

const QualitativePillarsEmpty: React.FC<IQualitativePillarsEmpty> = ({
    message = 'Qualitative analysis is unavailable for this company right now.',
    title = 'No qualitative analysis yet',
}) => {
    // 1.6.1. HOOKS & API CALLS ....................................................................
    // 1.6.1. END ....................................................................................

    // 1.6.2. FUNCTIONS & LOCAL VARIABLES ..........................................................
    // 1.6.2. END ....................................................................................

    // 1.6.3. RENDER .................................................................................
    return (
        <QualitativePillarsStateContainer data-testid="qualitative-pillars-empty">
            <QualitativePillarsStateTitle>{title}</QualitativePillarsStateTitle>
            <QualitativePillarsStateDescription>{message}</QualitativePillarsStateDescription>
        </QualitativePillarsStateContainer>
    );
    // 1.6.3. END ....................................................................................
};

// 1.6. END ..........................................................................................

export default QualitativePillarsEmpty;

// END FILE ##########################################################################################
