// [ BACKEND > PRESENTATION > ALPACA ERROR STATUS > TESTS ] ##########################################

// 1.1. EXTERNAL DEPENDENCIES ........................................................................
import assert from "node:assert/strict";
import { describe, it } from "node:test";
// 1.1. END ..........................................................................................

// 1.2. INTERNAL DEPENDENCIES ........................................................................
import { statusForAlpacaError } from "./index.js";
// 1.2. END ..........................................................................................

// 1.3. TEST CASES ...................................................................................
describe("statusForAlpacaError", () => {
  // 1.3.1. MAPS FORBIDDEN TO 403 ....................................................................
  it("maps forbidden to 403", () => {
    assert.equal(statusForAlpacaError("forbidden"), 403);
  });
  // 1.3.1. END ......................................................................................

  // 1.3.2. MAPS INVALID REQUEST TO 422 ..............................................................
  it("maps invalid request to 422", () => {
    assert.equal(statusForAlpacaError("invalid-request"), 422);
  });
  // 1.3.2. END ......................................................................................

  // 1.3.3. MAPS RATE LIMIT TO 429 ...................................................................
  it("maps rate limit to 429", () => {
    assert.equal(statusForAlpacaError("rate-limit"), 429);
  });
  // 1.3.3. END ......................................................................................

  // 1.3.4. MAPS TIMEOUT TO 504 ......................................................................
  it("maps timeout to 504", () => {
    assert.equal(statusForAlpacaError("timeout"), 504);
  });
  // 1.3.4. END ......................................................................................

  // 1.3.5. MAPS UPSTREAM FAILURES TO 502 ............................................................
  it("maps authentication, invalid response, and provider failures to 502", () => {
    assert.equal(statusForAlpacaError("authentication"), 502);
    assert.equal(statusForAlpacaError("invalid-response"), 502);
    assert.equal(statusForAlpacaError("provider"), 502);
  });
  // 1.3.5. END ......................................................................................
});
// 1.3. END ..........................................................................................

// END FILE ##########################################################################################
